const you = document.getElementById("You");
const ocultar =  document.getElementById("ocultar");
const iframe = document.getElementById("iframe");
const ch = document.getElementById("chat");
const oc = document.getElementById("ocultarC")
const txt = document.getElementById("textarea");
const fav = document.getElementById("favi");
const en = document.getElementById("enter");
const Gema = document.getElementById("Gema");
const live = document.getElementById("live")
const plys = document.getElementById("plys")
const pc = document.getElementById("pc")
const tr = document.getElementById("tr")
const sub = document.getElementById("sub")
const btn = document.getElementById("btn")
const baixo = document.getElementById("Baixo")
const ba1 = document.getElementById("b1");
const ba2 = document.getElementById("b2");
const ba3 = document.getElementById("b3");
const stick = document.getElementById("stick")
const hora = document.getElementById("horas")
const mil = document.getElementById("milhões")
var i=0;
function ocultC(){
    if(!i){
        ch.style.display="flex";
        ch.style.marginTop="-1000px";
        you.style.display="flex";
        you.style.marginTop="-1000px";
        txt.style.display="none"
        fav.style.display="none"
        en.style.display="none"
        oc.style.marginLeft="215px"
        oc.style.marginTop="-190px"
        iframe.style.width= "1870px";
       iframe.style.display="block";
       iframe.style.margin="auto";
       iframe.style.marginLeft="-1px";
       iframe.style.marginTop="-100px";
       Gema.style.width="200px";
       Gema.style.marginLeft="-150px";
       live.style.marginLeft="-175px";
       live.style.marginTop="-5px"
       plys.style.fontSize="90px"
       plys.style.marginRight="100px"
       plys.style.marginTop="-230px"
       pc.style.fontSize="36px";
       pc.style.marginTop="-120px";
       pc.style.marginRight="-270px";
       pc.style.width="1200px";
       tr.style.marginTop="-30px"
       tr.style.marginRight="80px";
       tr.style.fontSize="35px";
       sub.style.marginRight="-140px"
       sub.style.marginTop="-2em"
       btn.style.marginRight="-600px"
       btn.style.marginTop="-190px"
       baixo.style.marginTop="200px"
       baixo.style.marginLeft="100px"
       baixo.style.height="140px"
       baixo.style.width="109em"
       ba1.style.fontSize="50px"
       ba2.style.fontSize="30px"
       ba2.style.float="left"
       ba2.style.marginLeft="-22em"
       ba3.style.fontSize="20px"
       ba3.style.marginTop="4em"
       stick.style.width="60px"
       stick.style.height="60px"
       stick.style.marginLeft="50px"
       stick.style.marginTop="-2em"
       mil.style.marginLeft="120px"
       hora.style.marginLeft="120px"
       i=1
    }
    else{
        ch.style.display="inline";
        ch.style.marginTop="-710px";
        txt.style.display="inline"
        fav.style.display="inline"
        fav.style.marginTop="-14.5em"
        en.style.display="inline"
        en.style.marginBottom="20em"
        oc.style.marginLeft="-1px"
        oc.style.marginTop="2px"
        iframe.style.width= "1430px";
       iframe.style.display="block";
       iframe.style.margin="auto"
       iframe.style.marginRight="265px"
       iframe.style.marginTop="-100px"
       you.style.display="inline"
       you.style.marginTop="-5px";
       Gema.style.width="150px";
       Gema.style.marginLeft="45px";
       live.style.marginLeft=" 1px";
       plys.style.fontSize="50px"
       plys.style.float="right"
       plys.style.marginRight="-40px"
       plys.style.marginTop="-170px"
       pc.style.fontSize="20px";
       pc.style.marginTop="-110px";
       pc.style.float="right"
       pc.style.marginRight="-65px";
       pc.style.width="850px";
       tr.style.marginRight="-60px";
       tr.style.fontSize="24px";
       tr.style.marginTop="-45px"
       sub.style.marginRight="-70px"
       sub.style.marginTop="-2.5em"
       btn.style.marginRight="-420px"
       btn.style.marginTop="-150px"
       baixo.style.marginTop="125px"
       baixo.style.marginLeft="230px"
       baixo.style.height="90px"
       baixo.style.width="1420px"
       ba1.style.fontSize="30px"
       ba2.style.fontSize="15px"
       ba2.style.float="left"
       ba2.style.marginLeft="-31em"
       ba2.style.marginTop="25px"
       ba3.style.fontSize="15px"
       ba3.style.marginTop="60px"
       ba3.style.marginLeft="1em"
       stick.style.width="50px"
       stick.style.height="35px"
       stick.style.marginLeft="-30px"
       stick.style.marginTop="-1em"
       mil.style.marginLeft="30px"
       hora.style.marginLeft="20px"
        i=0
    }
}